name: build

on:
  # Trigger the workflow on push to main or any pull request
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        platform: [ubuntu-18.04]
        python-version: [3.8, 3.9]
        # torchaudio-version: [0.10.2, 0.9.1, 0.8.1]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Linux dependencies
      run: sudo apt-get install -y libsndfile1-dev sox

    - name: Upgrade pip
      run: pip3 install --upgrade pip

    - name: Install wheel and setuptools
      run: pip3 install --upgrade wheel setuptools

    # - name: Install PyTorch & Torchaudio
    #   run: pip3 install torchaudio==${{ matrix.torchaudio-version }}

    - name: Install MiniASR
      run: pip3 install --editable

    - name: Install setuptools v59.5.0
      run: pip3 install setuptools==59.5.0

    - name: Check coding style by script/format.py
      run: |
        ./script/format.py --check
